<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        (async function(){
            try {
                let res1 = await promise2();
                console.log(res1);
                let res2 = await promise1();
                console.log(res2);
            } catch (error) {
                //这捕获 await 在多个异步中,任意一个出现的错误
                // 多个异步中:有一个出现错误其他的都不执行了
                console.log(error);
            }
        })()

        function promise1() {
            return new Promise((resolve, reject) => {
                console.log('异步任务一 开始');
                setTimeout(() => {
                    console.log('任务一 有结果了');
                    resolve('success one');
                }, 1000);
            })
        }

        function promise2() {
            return new Promise((resolve, reject) => {
                console.log('异步任务二 开始');
                setTimeout(() => {
                    console.log('任务二 有结果了');
                    reject('error 2');
                }, 2000);
            })
        }

    </script>
</body>

</html>